providers = ["php"]

[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo"]

[phases.install]
cmd = "php -r 'copy(\"https://getcomposer.org/installer\", \"composer-setup.php\");' && php composer-setup.php && php -r 'unlink(\"composer-setup.php\");' && mv composer.phar /usr/local/bin/composer && composer install --no-dev"

[build]
cmd = "composer dump-autoload -o"

[start]
cmd = "php -S 0.0.0.0:3000 -t public"
