providers = ["php"]

[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "composer"]

[install]
cmd = "composer install --no-dev"

[build]
cmd = "composer dump-autoload -o"

[start]
cmd = "php -S 0.0.0.0:8000 -t public"
