providers = ["ruby"]

[phases.setup]
nixPkgs = ["ruby_3_3"]

[phases.install]
cmds = ["bundle install --deployment"]

[phases.build]
cmds = ["bundle exec rake assets:precompile"]

[phases.start]
cmd = "bundle exec puma -b tcp://0.0.0.0:3000"
