providers = ["ruby"]

[phases.setup]
nixPkgs = ["ruby_3_3"]

[install]
cmd = "bundle install --deployment"

[build]
cmd = "bundle exec rake assets:precompile"

[start]
cmd = "bundle exec puma -b tcp://0.0.0.0:3000"
