providers = ["elixir"]

[phases.setup]
nixPkgs = ["beam", "elixir"]

[phases.install]
cmds = ["mix local.hex --force", "mix deps.get"]

[phases.build]
cmds = ["mix release"]

[phases.start]
cmd = "_build/prod/rel/app/bin/app start"
