providers = ["elixir"]

[phases.setup]
nixPkgs = ["beam", "elixir"]

[install]
cmd = "mix local.hex --force && mix deps.get"

[build]
cmd = "mix release"

[start]
cmd = "_build/prod/rel/app/bin/app start"
