providers = ["java"]

[phases.setup]
nixPkgs = ["jdk21", "maven"]

[phases.install]
cmds = ["mvn dependency:resolve"]

[phases.build]
cmds = ["mvn package -DskipTests"]

[phases.start]
cmd = "java -jar target/app.jar"
